### PR TITLE
Update inotify.cr

### PR DESCRIPTION
**Pull request by petoem**
Update compatibility to inotify.cr 1.0.0

### CODE REVIEW

**Comment by j8r** [comment]
Snap, I've pushed a commit to update the lib when I see you in my notifications starring the project.
What I haven't done is a `shards.lock` where we can pin the version of Inotify (I prefer to put it here)

**Comment by j8r** [comment]
Another thing, we can mention your library with a link in the `README.md` :slightly_smiling_face:

**Comment by petoem** [comment]
Isn't `shards.lock` only for applications?

**Comment by j8r** [comment]
Right, after a test `shards` doesn't take `shard.lock` of libraries into account.
For the version in `shard.yml`, I think `~> 1.0.0` would be better to match potential patch releases.
For the Inotify mention, you can add something like:
`[Inotify.cr](https://github.com/petoem/inotify.cr) is used in Linux` just before the Installation section.

**Review by j8r — APPROVED** [review]

**Comment by j8r** [comment]
Thanks @petoem :smiley:

**Pull request merged**
